### ISSUE TITLE
Deprecation warnings with rake 0.9.0

### ISSUE THREAD

**Issue by adamtrilling** [datamapper/dm-rails#10]
I just built a new dev environment, and ended up with the brand-new rake 0.9.0.  It causes some deprecation warnings in dm-rails:

WARNING: 'task :t, arg, :needs => [deps]' is deprecated.  Please use 'task :t, [args] => [deps]' instead.
    at <rvm path>/dm-rails-1.1.0/lib/dm-rails/railties/database.rake:67
WARNING: 'task :t, arg, :needs => [deps]' is deprecated.  Please use 'task :t, [args] => [deps]' instead.
    at <rvm path>/dm-rails-1.1.0/lib/dm-rails/railties/database.rake:72

Not sure if you can fix these without breaking any intended backwards compatibility, but just in case you wanted to know...

**Comment by tpitale** [comment]
This is at least fixed on master. Not sure if a gem has been released with this.
