### ISSUE TITLE
composite keys in a rails project

### ISSUE THREAD

**Issue by Ragmaanir** [datamapper/dm-rails#12]
Im not sure if this is caused by dm-rails.
The code is here:
https://gist.github.com/1011318

You can execute the _setup.sh (copy & paste to terminal) which should setup a rails 3 project with a Gemfile, rspec, the models and one spec. The spec should fail (at least when i execute it it fails with "expected: nil got: nil").

It seems like during the DataMapper.auto_migrate! the columns in the Database for Friendship.request are not created. In a standalone test with the same models though it works and Friendship has one :request_sender_id and :request_receiver_id property. The standalone-spec is here: https://gist.github.com/1010908

Am i doing something wrong or is this a dm-rails/dm-migration/whatever bug?

**Comment by tpitale** [comment]
This _could_ be either a dm-migrations or sqlite issue.

If this is still a problem, can you update the gist again. It's no longer runnable.

I'll reopen if this is an issue still.
