### ISSUE TITLE
Rails 3.0 compatibility

### ISSUE THREAD

**Issue by coffeeworks** [datamapper/dm-rails#29]
It seems like dm-rails 1.2 is the only version that is compatible with ruby 1.9.3, but dm-rails depends on rails ~> 3.1.0, is that neccesary? could it support rails ~> 3.0.10 ?

**Comment by tpitale** [comment]
Looks like this should be workable now: https://github.com/datamapper/dm-rails/blob/master/dm-rails.gemspec#L20-L21
