### ISSUE TITLE
SessionStore does not write session if internals of session['flash'] are modified

### ISSUE THREAD

**Issue by devrandom1** [datamapper/dm-rails#30]
`SessionStore::Session.set_session` gets the memorized session model instance from env, then updates session_data.  However, session.dirty? is false even if the internals of the flash changed, because they were already modified by the flash object.

The fix seems to be to replace:

`session            = get_session_resource(env, sid)`

with

`session            = find_session(sid)`

to get a fresh copy.

**Comment by tpitale** [comment]
This is unlikely to be fixed. We may even remove this implementation from the session store. Dirtiness is dependent on object id changing, but when you change the internals of a hash, it does not change, IIRC.

Will take a look again to confirm.

**Comment by tpitale** [comment]
This is definitely a dirtiness tracking issue for the internals of a hash. Unlikely to ever be fixed afaict. There are some hacks around tracking, but I don't think they apply well here.
