### ISSUE TITLE
gem dependency clash with rails 3.2.1

### ISSUE THREAD

**Issue by jessereynolds** [datamapper/dm-rails#36]
Hello

I'm new to the world of dm-rails, so this is probably just a newbee thing. 

I found that following the instructions in the README failed due to a clash on activepack version requirements, as sass-rails wants actionpack version 3.1.x ...

    jesse@Heart-of-Gold $ bundle install
    Fetching source index for http://rubygems.org/
    Bundler could not find compatible versions for gem "actionpack":
      In Gemfile:
        sass-rails (~> 3.1.5) ruby depends on
          actionpack (~> 3.1.0) ruby
    
        actionpack (3.2.1)

Commenting out the following lines and running 'bundle update' once more fixes it for now...

    #group :assets do                                                                                                                          
    #  gem 'sass-rails',   '~> 3.1.5'                                                                                                          
    #  gem 'coffee-rails', '~> 3.1.1'                                                                                                          
    #  gem 'uglifier', '>= 1.0.3'                                                                                                              
    #end

**Comment by tpitale** [comment]
I think this should all be working. If you're having trouble with the latest Rails 4, please leave a comment.
