### ISSUE TITLE
active record config errors on app generation

### ISSUE THREAD

**Issue by lukeholder** [datamapper/dm-rails#37]
rails 3.2.2

after generating a new rails app with

`rails new project_name -m http://datamapper.org/templates/rails.rb`

when trying to use the generators i got a error referencing active_record in the development.rb file in environments.

after commenting out the offending lines referencing active record:

LN 26: `config.active_record.mass_assignment_sanitizer = :strict`

LN 30: `config.active_record.auto_explain_threshold_in_seconds = 0.5`

I was able to use the generator to correctly generate a scaffold.

I believe the `http://datamapper.org/templates/rails.rb` script needs to be updated.

Thanks.

**Comment by tpitale** [comment]
Those templates are definitely gone now, so closing this.
