### ISSUE TITLE
migrate task: Use Rails config.paths for location of migration files

### ISSUE THREAD

**Issue by paulwalker** [datamapper/dm-rails#38]
Rails now allows configuration of an array of paths for the location of migration files.  The path should not be hardcoded and instead the paths should be read from the configuration.

change (in load task):

    FileList['db/migrate/*.rb'].each do |migration|

to: 

    paths = Rails.configuration.paths['db/migrate'].map { |p| p + '/*.rb' }
    FileList[paths].each do |migration|

also in actual migrate task change:

    migrate_task = if Dir['db/migrate/*.rb'].empty?

to:

    migrate_task = if Rails.configuration.paths['db/migrate'].all? { |p| Dir[p + '/*.rb'].empty? }

**Comment by tpitale** [comment]
Would love a PR for this. Thanks @paulwalker!
